version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "ping_pong"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  server:
    image: bonk123123/ping-pong-online-client:latest

    ports:
      - 5000:5000

  client:

    image: bonk123123/ping-pong-online-server:latest

    ports:
      - 5021:5021

    # network_mode: host

    depends_on:
      - server